---
- name: Configure Nginx with SSL (Certbot)
  hosts: app
  become: yes
  vars:
    domain: acc.buut.tiao1.be
    webroot_path: /var/www/{{ domain }}

  tasks:
    - name: Install required packages
      apt:
        name: 
          - nginx
          - certbot
          - python3-certbot-nginx
        state: present
        update_cache: yes

    - name: Create webroot directory
      file:
        path: "{{ webroot_path }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Ensure Nginx configuration file exists
      file:
        path: /etc/nginx/sites-available/{{ domain }}
        state: touch
        owner: root
        group: root
        mode: '0644'


    - name: Configure Nginx for Certbot verification
      blockinfile:
        path: /etc/nginx/sites-available/{{ domain }}
        block: |
          server {
              listen 80;
              server_name {{ domain }};

              location /.well-known/acme-challenge/ {
                  root {{ webroot_path }};
              }

              location / {
                  proxy_pass http://127.0.0.1:5001;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
      notify: Reload Nginx

    - name: Enable Nginx site configuration
      file:
        src: /etc/nginx/sites-available/{{ domain }}
        dest: /etc/nginx/sites-enabled/{{ domain }}
        state: link

    - name: Test Nginx configuration
      command: nginx -t

    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

    - name: Obtain SSL certificate with Certbot
      command: >
        certbot certonly --webroot -w {{ webroot_path }}
        -d {{ domain }}
        --non-interactive --agree-tos --email admin@acc.buut.tiao1.be
      register: certbot_result

    - name: Configure Nginx to use Let's Encrypt certificate
      blockinfile:
        path: /etc/nginx/sites-available/{{ domain }}
        marker: "# {mark} Let's Encrypt SSL"
        block: |
          server {
              listen 443 ssl;
              server_name {{ domain }};

              ssl_certificate /etc/letsencrypt/live/{{ domain }}/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/{{ domain }}/privkey.pem;
              ssl_protocols TLSv1.2 TLSv1.3;
              ssl_ciphers 'TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384';

              location / {
                  proxy_pass http://127.0.0.1:5001;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
      notify: Reload Nginx

    - name: Reload Nginx to apply SSL configuration
      service:
        name: nginx
        state: reloaded

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
